In [36]:
import random

In [57]:
class NutritionRecommender:
    def __init__(self, age, weight, dietary_preferences):
        self.age = age
        self.weight = weight
        self.dietary_preferences = dietary_preferences

        self.meal_options = {
            "vegetarian": ["lentil soup", "vegetable curry", "quinoa salad"],
            "vegan": ["vegetable stir-fry", "hummus and pita bread", "fruit smoothie"],
            "non-vegetarian": ["chicken breast with vegetables", "fish with rice", "steak with salad"],
            "gluten-free": ["salmon with sweet potato", "chicken stir-fry with rice noodles", "vegetable soup"],
            "low-carb": ["grilled chicken with asparagus", "salmon with cauliflower mash", "spinach salad with feta cheese"]
        }

    def recommend_meal(self, meal_time):

        if self.age < 30:
            pass
        elif self.age > 60:
            pass
        if self.weight < 120:
            pass
        elif self.weight > 200:
            pass

        meal_options = self.meal_options[self.dietary_preferences]

        meal = random.choice(meal_options)

        return meal

    def recommend_meal_plan(self):

        breakfast = self.recommend_meal("breakfast")
        lunch = self.recommend_meal("lunch")
        dinner = self.recommend_meal("dinner")

        return breakfast, lunch, dinner

user_data = {
    "age": 35,
    "weight": 150,
    "dietary_preferences": "vegetarian"
}

nutrition_recommender = NutritionRecommender(**user_data)
meal_plan = nutrition_recommender.recommend_meal_plan()
print("Meal Plan:")
print("Breakfast:",meal_plan[0])
print("Lunch:",meal_plan[1])
print("Dinner:",meal_plan[2])

Meal Plan:
Breakfast: quinoa salad
Lunch: vegetable curry
Dinner: quinoa salad

In [58]:
import pandas as pd
import numpy as np
import random

# Define the number of rows you want in the CSV
num_rows = 100

# Create random data
data = {
    'User id': [f'UID{str(i).zfill(4)}' for i in range(1, num_rows+1)],
    'Age': np.random.randint(18, 65, size=num_rows),  # Age between 18 and 65
    'Weight': np.random.uniform(50.0, 120.0, size=num_rows),  # Weight between 50kg and 120kg
    'Dietary_Preferences': random.choices(['Vegan', 'Vegetarian', 'Non-Vegetarian', 'Keto', 'Paleo'], k=num_rows),
    'Recommended_Calories': np.random.uniform(1500, 3000, size=num_rows)  # Recommended Calories between 1500 and 3000
}

# Create DataFrame
df = pd.DataFrame(data)

# Save DataFrame to CSV
df.to_csv('random_user_data.csv', index=False)

print("CSV file created successfully!")

CSV file created successfully!

In [59]:
df

    User id  Age      Weight Dietary_Preferences  Recommended_Calories
0   UID0001   22   84.995099          Vegetarian           2124.396381
1   UID0002   50   70.111556               Paleo           2447.554686
2   UID0003   32   53.146326                Keto           2530.236213
3   UID0004   61  101.777903               Vegan           2979.747886
4   UID0005   62   89.094202      Non-Vegetarian           2295.283041
..      ...  ...         ...                 ...                   ...
95  UID0096   30   93.555936          Vegetarian           2761.094117
96  UID0097   48   86.778235      Non-Vegetarian           1786.929484
97  UID0098   58   56.851881               Paleo           2962.157244
98  UID0099   42   54.132976      Non-Vegetarian           2800.724625
99  UID0100   41   81.014153               Paleo           2422.791097

[100 rows x 5 columns]